### ISSUE TITLE
🌟 Version 1.0 Release Roadmap.

### ISSUE THREAD

**Issue by diamantdev** [diamantdev/transhlate#1]
There is all the roadmap for the 1.0 release.

### Note:
In the actual commit before this issues is created (df208fbd9d1a9cded109ccb57bb958fe32e9914a), only the discord bot was in this monorepo, but the repo will include more than a discord bot.

## Identity:

- [ ] 🖼️ New design identity (logo, color palette, fonts...) for the project.
- [x] 👤 New name. (Done, from G. Translator to Transhlate.)

## Transhlators:

Transhlators are a term to mean the series of languages used for translate a text.

- [ ] ➕ **Add a new transhlators at the release** (called the released) for having 20 transhlators max in the discord bot (17 + the randomiser + the User and Server one.) and 16 in the Google Sheet.

## Discord Bot:

The Discord bot is already in the v0.4, see the release page to watch the description and their changelogs.

### Additions:

- [ ] ➕ **Translate Randomiser**: Translate any text completely random, including the number of languages random between 10 and 200, and each language random too.
- [ ] ➕ **Translate Mixed**: Translate any text to 3 differents Transhlators at the same time.
- [ ] ➕ **New share feature**: User can share their result with the new Transhlator app website.
- [ ] ➕ **New Settings feature**: User and server moderators can set settings for set their default options for users (as users) and whole server or channels. (as server moderators)
- [ ] ➕ **Users and Servers custom transhlators**: Users and Servers moderators can create their own custom transhlators. 

### Improvement:

- [ ] 🚧 The context menu will have only one command associated, and user will have 2 new buttons for change the translator and change the final language. (Using discord dropdown.)
- [ ] 🚧 The `/translate` command will have new option to show publicly (by default) or to hide and only show to user.
- [ ] 🚧 The `/translate` command will detect if inside of the text field is an id. If it is, the bot will translate the message id instead of the number. If not, or if the bot can't reach the message by ID, the bot will generate an error embed with the possibility to translate the ID number.
- [ ] 🚧 Switch from pastebin to the internal website for all the text who was too long to show in embeds.

## Google sheet:

The Google Sheet is the original project to all this stuff, started in summer 2021, the Google sheet was made because it's the easiest and the free way to communicate over Google Translate. (via the [GOOGLETRANSLATE](https://support.google.com/docs/answer/3093331?hl=en) formula.

### In the sheet itself:

- [ ] 🖼️ Apply the new design identity to the Google Sheet.
- [ ] 🚧 Optimise the sheet.
- [ ] ➕ Add the 

### In this repo:

- [ ] 📄 Create the Google sheet documentation.
- [ ] 🔗 Create an easy link to generate Google sheet to people.

## Website:

The new website will be a way to show all the differents projects (the bot, the google sheet...) about Transhlate, and will host the documentation, shared translations, the API and more...
Dev using svelte and tailwindcss.

### Pages:

- [ ] 🏠 Homepage
- [ ] ℹ️ Informations
- [ ] 🔨 Projects
- [ ] 🤖 API
- [ ] 📄 Documentation

### Features:

- [ ] 🤖 Create an API using express and glitch.
- [ ] 🔗 Create a share service for discord bot using database and message ID. (database for stocking all the long messages)
- [ ] ✍🏻 Create a database for stocking all the long text than don't fit in an embed.
- [ ] 💻 Have 3 transhlators to try in the front page. (The originals, the realased, and one exclusive to the website)

## Documentations:

All the stuffs to write some documentations:

- [ ] Terms of the project. (Transhlators, languages...)
- [ ] How to use the bot
- [ ] How to use the google sheet
- [ ] How to create their own transhlators for the discord bot
- [ ] API
- [ ] languages of transhlators.

#### And maybe other thing too than it will not be showed in this roadmap.

**Comment by diamantdev** [comment]
Update:

API Will not be part of 1.0, due of internal test who the API send response more than a minute or more. The website will use internal program cloned from the discord bot and not the API.
